-- Add your tables here.
-- Example:
-- CREATE TABLE IF NOT EXISTS users (
--   id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
--   email TEXT NOT NULL,
--   created_at TIMESTAMPTZ DEFAULT now()
-- );
